// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID        uuid.UUID
	Filename  string
	Size      int64
	MimeType  string
	Status    string
	CreatedAt time.Time
}
