// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :exec

INSERT INTO files (id, filename, size, mime_type, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateFileParams struct {
	ID       uuid.UUID
	Filename string
	Size     int64
	MimeType string
	Status   string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.ExecContext(ctx, createFile,
		arg.ID,
		arg.Filename,
		arg.Size,
		arg.MimeType,
		arg.Status,
	)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, filename, size, mime_type, status, created_at, updated_at FROM files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Size,
		&i.MimeType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
