// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :exec

INSERT INTO files (id, filename, size, mime_type, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateFileParams struct {
	ID       uuid.UUID
	Filename string
	Size     int64
	MimeType string
	Status   string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.ExecContext(ctx, createFile,
		arg.ID,
		arg.Filename,
		arg.Size,
		arg.MimeType,
		arg.Status,
	)
	return err
}

const createResult = `-- name: CreateResult :one
INSERT INTO results (file_id, output_data)
VALUES ($1, $2)
RETURNING id, file_id, output_data, created_at
`

type CreateResultParams struct {
	FileID     uuid.UUID
	OutputData string
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (Result, error) {
	row := q.db.QueryRowContext(ctx, createResult, arg.FileID, arg.OutputData)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OutputData,
		&i.CreatedAt,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, filename, size, mime_type, status, created_at, updated_at FROM files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Size,
		&i.MimeType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResultByFileID = `-- name: GetResultByFileID :one
SELECT id, file_id, output_data, created_at FROM results WHERE file_id = $1
`

func (q *Queries) GetResultByFileID(ctx context.Context, fileID uuid.UUID) (Result, error) {
	row := q.db.QueryRowContext(ctx, getResultByFileID, fileID)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OutputData,
		&i.CreatedAt,
	)
	return i, err
}

const updateFileStatus = `-- name: UpdateFileStatus :exec
UPDATE files
SET status = $2
WHERE id = $1
`

type UpdateFileStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFileStatus, arg.ID, arg.Status)
	return err
}
